In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:
import numpy as np
import cv2
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
# Define the train directory
train_dir = '/content/drive/MyDrive/Eugenia & Thasniya - Term paper/New Plant Diseases Dataset(Augmented)/train'

# Define the image size
img_size = (256, 256)

# Initialize the lists to store the images and labels
train_img = []
train_label = []

In [4]:
# Loop through the folders in the train directory
for folder in os.listdir(train_dir):
    # Get the list of images in the folder
    img_list = os.listdir(os.path.join(train_dir, folder))

    # Loop through the images in the folder
    for img in img_list:
        # Get the path to the image
        img_path = os.path.join(train_dir, folder, img)

        # Read the image using OpenCV
        img = cv2.imread(img_path)

        # Resize the image to the specified size
        img = cv2.resize(img, img_size)

        # Append the image to the list of train images
        train_img.append(img)

        # Append the label to the list of train labels
        if folder == 'Tomato___Septoria_leaf_spot':
            train_label.append(0)
        elif folder == 'Tomato___Spider_mites Two-spotted_spider_mite':
            train_label.append(1)
        elif folder == 'Tomato___Target_Spot':
            train_label.append(2)
        elif folder == 'Tomato___Tomato_Yellow_Leaf_Curl_Virus':
            train_label.append(3)
        elif folder == 'Tomato___Tomato_mosaic_virus':
            train_label.append(4)
        elif folder == 'Tomato___healthy':
            train_label.append(5)


In [5]:
# Convert the lists to numpy arrays
train_img = np.array(train_img)
train_label = np.array(train_label)

# Reshape the train images to 1D arrays
train_img = train_img.reshape(train_img.shape[0], -1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(train_img, train_label, test_size=0.2, random_state=42)

# Create a KNN model
knn = KNeighborsClassifier(n_neighbors=5)


In [6]:
# Train the model
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Define a function to predict the disease status of a single image
def predict_disease(image_path):
    # Read the image using OpenCV
    img = cv2.imread(image_path)

    # Resize the image to the specified size
    img = cv2.resize(img, img_size)

    # Reshape the image to a 1D array
    img = img.reshape(1, -1)

    # Make a prediction using the trained model
    prediction = knn.predict(img)

    # Return the predicted disease status
    if prediction[0] == 0:
        return 'Septoria leaf spot'
    elif prediction[0] == 1:
        return 'Spider mites Two-spotted spider mite'
    elif prediction[0] == 2:
        return 'Target Spot'
    elif prediction[0] == 3:
        return 'Tomato Yellow Leaf Curl Virus'
    elif prediction[0] == 4:
        return 'Tomato mosaic virus'
    elif prediction[0] == 5:
        return 'Healthy'

# Test the function
image_path = '/content/drive/MyDrive/Eugenia & Thasniya - Term paper/New Plant Diseases Dataset(Augmented)/train/Tomato___Spider_mites Two-spotted_spider_mite/Copy of e136c0bb-0587-431b-b412-0abe8eea294a___Com.G_SpM_FL 8919.JPG'
print(predict_disease(image_path))

Accuracy: 0.45
Spider mites Two-spotted spider mite


In [8]:
import numpy as np
import cv2
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
# Define the train directory
train_dir = '/content/drive/MyDrive/Eugenia & Thasniya - Term paper/New Plant Diseases Dataset(Augmented)/train'

# Define the image size
img_size = (256, 256)

# Initialize the lists to store the images and labels
train_img = []
train_label = []

# Loop through the folders in the train directory
for folder in os.listdir(train_dir):
    # Get the list of images in the folder
    img_list = os.listdir(os.path.join(train_dir, folder))

    # Loop through the images in the folder
    for img in img_list:
        # Get the path to the image
        img_path = os.path.join(train_dir, folder, img)

        # Read the image using OpenCV
        img = cv2.imread(img_path)

        # Resize the image to the specified size
        img = cv2.resize(img, img_size)

        # Append the image to the list of train images
        train_img.append(img)

        # Append the label to the list of train labels
        if folder == 'Tomato___Septoria_leaf_spot':
            train_label.append(0)
        elif folder == 'Tomato___Spider_mites Two-spotted_spider_mite':
            train_label.append(1)
        elif folder == 'Tomato___Target_Spot':
            train_label.append(2)
        elif folder == 'Tomato___Tomato_Yellow_Leaf_Curl_Virus':
            train_label.append(3)
        elif folder == 'Tomato___Tomato_mosaic_virus':
            train_label.append(4)
        elif folder == 'Tomato___healthy':
            train_label.append(5)

# Convert the lists to numpy arrays
train_img = np.array(train_img)
train_label = np.array(train_label)

# Reshape the train images to 1D arrays
train_img = train_img.reshape(train_img.shape[0], -1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(train_img, train_label, test_size=0.2, random_state=42)

# Create a KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn.predict(X_test)

# Evaluate the KNN model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print('KNN Accuracy:', accuracy_knn)
print('KNN Classification Report:')
print(classification_report(y_test, y_pred_knn))
print('KNN Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_knn))

KNN Accuracy: 0.45
KNN Classification Report:
              precision    recall  f1-score   support

           0       0.45      0.36      0.40        14
           1       0.33      0.14      0.20         7
           2       0.57      0.44      0.50         9
           3       0.55      0.60      0.57        10
           4       1.00      0.33      0.50        12
           5       0.29      0.88      0.44         8

    accuracy                           0.45        60
   macro avg       0.53      0.46      0.43        60
weighted avg       0.56      0.45      0.45        60

KNN Confusion Matrix:
[[5 2 0 1 0 6]
 [0 1 1 2 0 3]
 [1 0 4 1 0 3]
 [2 0 2 6 0 0]
 [2 0 0 1 4 5]
 [1 0 0 0 0 7]]
